name: Release workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Xcode select
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
      - name: Build xcframeworks
        run: bash build.sh
      - name: Zip xcframeworks
        run: |
          for framework_path in XCFrameworks/*.xcframework
          do
            framework="$(basename "$framework_path")"
            (cd XCFrameworks && zip -r "../$framework.zip" "$framework")
          done
      - name: Upload Artifact
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.xcframework.zip"
          body:
            Release ${{ github.ref }}
            Automated release created by GitHub Actions.